### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by veronica365** [veronica365/recepies-app#15]
### Description

 - [Add link to the project](https://github.com/users/veronica365/projects/9)
 - We are two team members in our group
   -  Team member 1 - @mumo-esther 
   - Team member 2 - @veronica365

**Comment by brytebee** [comment]
Hi, @veronica365 & @mumo-esther 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

You have submitted a project, that loads a 404. Kindly ensure that the project and/or Kanban board is not private

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ishimwezachee** [comment]
Hi, @veronica365 & @mumo-esther 👋,

You've done a great job, go ahead and start the project  
![image](https://i.gifer.com/origin/16/162b41786d99b9d7e7b03549c4e19ae2_w200.gif)

##Highlights 

- Task are distributed equally  ✅
- All column are created in the board(todo, progress, review, Done) ✅
- All tasks from the requirements are added in Kanban board  ✅
